apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: evalbench-ssd-pvc
  namespace: evalbench-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: premium-rwo
