apiVersion: v1
kind: Service
metadata:
  name: eval-server
  namespace: evalbench-namespace
  annotations:
    cloud.google.com/neg: '{"exposed_ports":{"50051":{"name": "evalbench-directpath-neg"}}}'
spec:
  ipFamilyPolicy: RequireDualStack
  ipFamilies:
  - IPv6
  - IPv4
  ports:
  - name: grpc
    port: 50051
    protocol: TCP
    targetPort: 50051
  - name: ui
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: evalbench-eval-server
  type: ClusterIP