############################################################
### Dataset / Eval Items
############################################################
dataset_config: datasets/gemini-cli-tools/gemini-cli.evalset.json
dataset_format: gemini-cli-format
setup_directory: datasets/gemini-cli-tools/setup

# Model Configuration
model_config: datasets/model_configs/gemini_cli_model.yaml