[supervisord]
nodaemon=true
logfile = /tmp/supervisord.log
logfile_maxbytes = 50MB
logfile_backups=5


[program:evalbench_server]
command=python evalbench/eval_server.py
directory=/evalbench
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:evalbench_frontend]
command=gunicorn -w 4 -k gevent main:me --bind :3000 --forwarded-allow-ips="*"
directory=/evalbench/viewer
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
