[supervisord]
nodaemon=true

[program:evalbench_server]
command=uv run evalbench/eval_server.py
directory=/evalbench
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:evalbench_frontend]
command=uv run gunicorn -w 4 -k gevent main:me --bind :3000
directory=/evalbench/viewer
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
